sudo: false
language: groovy
jdk:
- oraclejdk7
cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy
  - $HOME/.sdkman
branches:
  only:
  - master
  - develop
before_install:
- rm -rf ~/.sdkman
- curl -s get.sdkman.io > ~/install_sdkman.sh
- chmod 775 ~/install_sdkman.sh
- ~/install_sdkman.sh
- echo "sdkman_auto_answer=true" > ~/.sdkman/etc/config
- source ~/.sdkman/bin/sdkman-init.sh
- GRAILS_VERSION=`grep '^app\.grails\.version=' ./application.properties | sed -e
  's/^app\.grails\.version=//g'`
- sdk install grails $GRAILS_VERSION || true
- sdk use grails $GRAILS_VERSION
before_script:
- mkdir -p ~/.grails; wget -q -O ~/.grails/settings.groovy https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/travis_grails_settings_new.groovy
- APP_VERSION=`grep '^app\.version=' ./application.properties | sed -e 's/^app\.version=//g'`
- MAVEN_REPO="ala-repo-snapshot"; grep '^app\.version=' ./application.properties |
  grep -q "\-SNAPSHOT"; if [ "$?" = "1" ]; then MAVEN_REPO="ala-repo-release"; fi;
script:
- grails clean && grails refresh-dependencies --non-interactive && grails prod war
  --non-interactive
after_success:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && travis_retry grails prod maven-deploy
  --repository=$MAVEN_REPO --non-interactive'
- '[ "${TRAVIS_BRANCH}" = "develop" ] && travis_retry curl -X POST --header "X-DEPLOY-KEY:
  ${DEPLOY_KEY}" https://volunteer-dev.ala.org.au/deploy/${APP_VERSION}'
env:
  global:
  - secure: 2MEDHHQ3nxNwf+YGgtC/GXx6kb0y4ixYA7Ia50pZHaN8xMHYdQ8EymKZJ8F9SXw0Feg9FsDc5I90lBJB8URYZZ4hPZN9+uj9crOvnOFMByvJpPikrQ6Yw8IdUjmYxHO/zv+kmOkqVnu6zCtS42olSM7ljeZs0PzW484Ci9w5eM4=
  - secure: iR4/BuaBNTKIGQENUdQQjzqhUgefvJnfyC0aK0j9NNLVwcH6lE//TAqz22n7TuzTDPq7My+0clua8DEbJt2k7/kMrbrAohCEXtWvI2pBa43GmB+D5/qOW0+MZk46QJ0pR+hmjHZ3U9DjhuNuF3w7zlNsUnItk70FlzV+sRrYgwg=
  - secure: pOWY7dwZRDcgsrYcwscdXHNPfhsPOSGhKNrG0G7AA4mhxaRKd9+1D31i5lhiA9qvbA0/lqD7A8Fnzvsf99MkUC6CSCQOh5n104UalYyiRQ/vhwfc0l9HdlCH86hShYq4PKvXA0hK5iCcIdltzn8pSnM4uHQiVKlbEJiX/qYNx7E=
notifications:
  hipchat:
    rooms:
      secure: GV/Ckk/00dAExEE4A2bb/6yuwIdTn6EQ63cdKOH0CSLYiUspolHbueuB/2bGVy1ErmL3+l6A/bwZidnGoiR6N3Id/SWRbXBnxn9s7VRFVPsoKLviJ1Xku2rMf/fFW+/PTm2FtEeGiGlvFcbzuIv+b6Vplm8ixIyosFdsEIB2mqc=
